### PR TITLE
update bower.json - angular version to 1.4.x

### PR DESCRIPTION
**Pull request by isoden**

### CODE REVIEW

**Comment by tsmd** [comment]
:+1:

**Comment by his-nagashima** [comment]
:+1:

**Comment by namba-nagi** [comment]
:+1:

**Comment by isoden** [comment]
Hello.

angular-awesome-slider is great! very useful plugin for angluar.
I want to use it. But, my project's angluar version is 1.4.x....

please check this pull request.

thanks!

**Comment by darul75** [comment]
thx u guys https://github.com/darul75/angular-awesome-slider/releases/tag/2.4.2

**Comment by isoden** [comment]
thanks!

**Pull request merged**
