### PR TITLE
add non-minified version and update bower

### PR DESCRIPTION
**Pull request by pgrodrigues**
Usually libraries/modules have a non-minified version next to the minifed version. It is useful for debugging and so on.

I changed your gruntfile to use concat to generate the non-minified version and then uglify to generate the minified version from the non-minified. Both are placed in `dist/`.

According to bower spec, minified files should not be included in the `main` property. There's still one minified css file that should be changed :P 

Not sure if this will break anything.

### CODE REVIEW

**Comment by darul75** [comment]
yeah it sound great, I integrate it asap, thx again, not forget put some stars in the sky ;)

**Comment by darul75** [comment]
I have to merge it, sorry for delay, quite busy

**Comment by kencaron** [comment]
+1 Debugging is very difficult at the moment

**Comment by darul75** [comment]
thanks a lot guys and sorry again for delay

**Pull request closed without merging**
