### PR TITLE
Add show or hide Labels

### PR DESCRIPTION
**Pull request by R0dgerV**

### CODE REVIEW

**Comment by darul75** [comment]
great good idea thx for providing this PR

**Comment by darul75** [comment]
I have renamed option to 'limits'

**Comment by R0dgerV** [comment]
Ок. no problem! )))))

**Comment by darul75** [comment]
options was there but not yet implemented...;)

**Comment by R0dgerV** [comment]
i modify locale code 
```
          scope.options.limits = scope.options.limits || true;
```

to
```
if (angular.isDefined(scope.options.limits)) {
   scope.options.limits = true;
} else
{
   scope.options.limits = false;
}
```

because `scope.options.limits` always `true`

**Comment by darul75** [comment]
how can it be always true ?

**Comment by R0dgerV** [comment]
If I'm not mistaken,

`scope.options.limits = scope.options.limits || true; ` = 
`bool(scope.options.limits) === false;`

But I could be wrong!

I always true

**Comment by darul75** [comment]
my mistake..

**Pull request merged**
